---
title: "simulate incidence - check"
author: "Pierre Nouvellet"
date: "2023-09"
output:
  html_document:
    self_contained: no
---

```{r , include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
rm(list=ls())


library(Hmisc)
library(coda)
library(EpiEstim)
library(incidence)
library(projections)
library(readxl)

devtools::load_all('.')

```

here check package work with perfect reporting!




# check MCMC with NB simulation


# simulate

```{r}

Scenarios <- as.data.frame(readxl::read_xlsx('../overdispersion-epidemic-data/overdispersion_scenarios.xlsx',
                               sheet = 1, range = 'A1:K73'))
si <- c(0,1)

i=64

# print(i)
input <- Scenarios[i,]
input$n_locations <- 13
input$R_min <- .7
input$R_max <- 1.4
  
I0 <- incidence::as.incidence(x = input$I0, dates = 1, interval = 1)

Rt <- MCMCEpiEstim::Rt_linear(inp = input)

if(!is.na(input$t_pi_change)){
  t_change_p <- input$t_pi_change*input$step+1
  
  Pi_t <- data.frame(t = c(Rt$t,tail(Rt$t,1)+1),
                     pi = c(rep(input$pi,t_change_p),
                            rep(input$pi2, nrow(Rt)+1-t_change_p )) )
}else{
  Pi_t <- input$pi
}
  
res <- MCMCEpiEstim::project_fct(I0 = I0,
                                 Rt = Rt,
                                 n_loc = input$n_locations,
                                 t_max = nrow(Rt),
                                 si = si,
                                 p = Pi_t,
                                 model = 'negbin',
                                 over = input$k)

sim <- list(input = input, I0 = I0, Rt = Rt, res = res)


matplot((sim$res$I_true[,-1]))
matplot((sim$res$I_obs[,-1]))
input
  
```



```{r}

# parameters
# for EpiEstim
t_window <- 7
mean_prior <- 5
std_prior <- 5

res_EpiEstim <- fct_EpiEstim(I0_t_import = sim$I0$timespan , I = sim$res$I_obs, #I_true ,
                             t_window = t_window, 
                             mean_prior = mean_prior, std_prior = std_prior,
                             si = si, overlap = FALSE)


plot(Rt$t,Rt$Rt,type = 'l', ylim = c(0,2.5))

for(i in 1:sim$input$n_locations){
  
  Hmisc::errbar(x = res_EpiEstim[[i]]$t_start, 
                y = res_EpiEstim[[i]]$`Median(R)`,
                yplus = res_EpiEstim[[i]]$`Quantile.0.975(R)`,
                yminus = res_EpiEstim[[i]]$`Quantile.0.025(R)`,
                col = i, errbar.col = i, 
                add=TRUE)
}



```



## Run MCMCEpiEstim 

```{r}

rep <- 1e4
# if truncation happen, put it here!
I_trunc <- MCMCEpiEstim::truncate_incidence(I0_t_import = sim$I0$timespan, I = sim$res$I_obs, 
                                            t_window = t_window, incidence_truncate = 1e3, t_truncate = 6 )

res_MCMC_EpiEstim_1 <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan , I= I_trunc, # I = sim$res$I_obs, # 
                                         t_window = t_window,
                                         mean_prior = mean_prior, std_prior = std_prior,
                                         res_EpiEstim = res_EpiEstim, overdispersion = TRUE, 
                                         rep = rep, thin = 10, param_agg = TRUE, p_reps = 1,overlap = FALSE,
                                         input = input)

res_MCMC_EpiEstim_2 <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan , I = sim$res$I_obs, 
                                              t_window = t_window,
                                             mean_prior = mean_prior, std_prior = std_prior,
                                             res_EpiEstim = res_EpiEstim, overdispersion = TRUE, 
                                             rep = rep, thin = 10, param_agg = TRUE, p_reps = input$pi,overlap = FALSE)

res_MCMC_EpiEstim_3 <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan , I = sim$res$I_obs, 
                                              t_window = t_window,
                                             mean_prior = mean_prior, std_prior = std_prior,
                                             res_EpiEstim = res_EpiEstim, overdispersion = TRUE, 
                                             rep = rep, thin = 10, param_agg = TRUE, p_reps = Pi_t,overlap = FALSE)

```


```{r}

dics <- data.frame(model = c('NB1','NB2','NB3'),
                   DIC = c(res_MCMC_EpiEstim_1$DIC[1],
                           res_MCMC_EpiEstim_2$DIC[1],
                           res_MCMC_EpiEstim_3$DIC[1]))
dics
```


## check

```{r}
LogL <- cbind(rowSums(res_MCMC_EpiEstim_1$logL),
              rowSums(res_MCMC_EpiEstim_2$logL))
R1 <- cbind(res_MCMC_EpiEstim_1$theta_R[,1],
            res_MCMC_EpiEstim_2$theta_R[,1])

layout(matrix(1:4,2,2))
plot(LogL[,1],ylim = range(c(LogL)))
lines(LogL[,2],col = 'red3',type = 'p',pch = 12)
# lines(LogL[,3],col = 'blue3',type = 'p',pch = 12)
# lines(LogL[,4],col = 'green3',type = 'p',pch = 12)

plot(R1[,1],ylim = range(c(R1)))
lines(R1[,2],col = 'red3',type = 'p',pch = 12)
# lines(R1[,3],col = 'blue3',type = 'p',pch = 12)
# lines(R1[,4],col = 'green3',type = 'p',pch = 12)


# others
# acf(res_MCMC_EpiEstim_Poiss1$theta_R[,1])
acf(res_MCMC_EpiEstim_1$theta_R[,1])

plot(res_MCMC_EpiEstim_1$theta_over , 
     ylim = range(c(res_MCMC_EpiEstim_1$theta_over,
                    res_MCMC_EpiEstim_2$theta_over)))

lines(res_MCMC_EpiEstim_2$theta_over,col = 'red3',type = 'p',pch = 12)
lines(res_MCMC_EpiEstim_3$theta_over,col = 'blue3',type = 'p',pch = 12)

quantile(res_MCMC_EpiEstim_1$theta_over, c(.5,.025,.975))
quantile(res_MCMC_EpiEstim_2$theta_over, c(.5,.025,.975))
quantile(res_MCMC_EpiEstim_3$theta_over, c(.5,.025,.975))

```

