---
title: "simulate incidence - check"
author: "Pierre Nouvellet"
date: "2023-09"
output:
  html_document:
    self_contained: no
---

```{r , include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
rm(list=ls())


library(Hmisc)
# remove.packages('EpiEstim')
# devtools::install_github("mrc-ide/EpiEstim",build = TRUE,ref = 'na_bug' )
library(EpiEstim)
library(incidence)
library(projections)
library(readxl)

# remove.packages('MCMCEpiEstim')
# devtools::install_github("pnouvellet/MCMCEpiEstim",build = TRUE)
# library(MCMCEpiEstim)
devtools::load_all('.')

```

here check package work with perfect reporting!




# check MCMC with NB simulation


# simulate

```{r}

Scenarios <- as.data.frame(readxl::read_xlsx('../overdispersion-epidemic-data/overdispersion_scenarios.xlsx',
                               sheet = 1, range = 'A1:K60'))
si <- c(0,1)

i=2

# print(i)
input <- Scenarios[i,]

# input$R_min <- 0.5
# input$R_max <- 3
# input$k <- .1
# # input$k <- 1e4
# input$pi <- 1 
# input$n_locations <- 1
# input$I0 <- 10

I0 <- incidence::as.incidence(x = input$I0, dates = 1, interval = 1)

Rt <- MCMCEpiEstim::Rt_linear(inp = input)

t_change_p <- input$t_pi_change*input$step+1
  if(is.na(t_change_p)){
    Pi_t <- data.frame(t = c(Rt$t,tail(Rt$t,1)+1),
                       pi = input$pi )
  }else{
    
    Pi_t <- data.frame(t = c(Rt$t,tail(Rt$t,1)+1),
                       pi = c(rep(input$pi,t_change_p),
                              rep(input$pi2, nrow(Rt)+1-t_change_p )) )
  }

res <- list()

for(k in 1:100)
{
  res[[k]] <- MCMCEpiEstim::project_fct(I0 = I0,
                                 Rt = Rt,
                                 n_loc = input$n_locations,
                                 t_max = nrow(Rt),
                                 si = si,
                                 p = Pi_t,
                                 model = 'negbin',
                                 over = input$k,
                                 k.seed = k,
                                 threshold_cumCase = 10)
}



sim <- list(input = input, I0 = I0, Rt = Rt, res = res)


matplot((sim$res[[1]]$I_true[,-1]))
matplot((sim$res[[1]]$I_obs[,-1]))
input
  

colSums(sim$res[[1]]$I_obs)
```

```{r}
# parameters
# for EpiEstim
t_window <- 7
mean_prior <- 5
std_prior <- 5

  replication_sc <- length(sim$res)
  input <- Scenarios[i,]

  res_EpiEstim <- list()
  res_MCMC_EpiEstim_Poiss1 <- list()
  res_MCMC_EpiEstim_NB1 <- list()

for(k in 1:replication_sc){
  # k=1
    print(k)
    # if truncation temporal or using max I, put it here
    I <- MCMCEpiEstim::truncate_incidence(I0_t_import = sim$I0$timespan,
                                          I = sim$res[[k]]$I_obs,
                                          t_window = t_window,
                                          incidence_truncate = 1e5)
    
    res_EpiEstim[[k]] <- fct_EpiEstim(I0_t_import = sim$I0$timespan,
                                      I = I ,
                                      t_window = t_window, 
                                      mean_prior = mean_prior, std_prior = std_prior,
                                      si = si, overlap = FALSE)
    
    
    
    ## Run MCMCEpiEstim 
    rep <- 1e3
    
    ## Poisson
    
    res_MCMC_EpiEstim_Poiss1[[k]] <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan,
                                                       I = sim$res[[k]]$I_obs, #I_true ,
                                                       t_window = t_window,
                                                       mean_prior = mean_prior,
                                                       std_prior = std_prior,
                                                       res_EpiEstim = res_EpiEstim[[k]],
                                                       overdispersion = FALSE, 
                                                       rep = rep, 
                                                       thin = 10, 
                                                       param_agg = TRUE, 
                                                       p_reps = Pi_t)
    
    ## NB
    
    res_MCMC_EpiEstim_NB1[[k]] <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan , 
                                                    I = sim$res[[k]]$I_obs, #I_true  ,
                                                    t_window = t_window,
                                                    mean_prior = mean_prior, 
                                                    std_prior = std_prior,
                                                    res_EpiEstim = res_EpiEstim[[k]], 
                                                    overdispersion = TRUE,
                                                    rep = rep, 
                                                    thin = 10, 
                                                    param_agg = TRUE, 
                                                    p_reps = 1)
    
    
    ## DICs
    
    dics <- data.frame(model = c('Pois1','NB1'),
                       DIC = c(res_MCMC_EpiEstim_Poiss1[[k]]$DIC[1],
                               res_MCMC_EpiEstim_NB1[[k]]$DIC[1]) )
  }
  
  # here keep track if poisson or neg binomial is better
  
  res <- list(input = input,
              res_EpiEstim = res_EpiEstim,
              res_MCMC_EpiEstim_Poiss1 = res_MCMC_EpiEstim_Poiss1,
              res_MCMC_EpiEstim_NB1 = res_MCMC_EpiEstim_NB1 )
  
```

```{r}
summary_performance <- function(x) {
  coverage_k <- sum(x$within_CI_k, na.rm = TRUE) / sum(!is.na(x$within_CI_k))
  coverage_R <- sum(x$within_CI_Rt, na.rm = TRUE) / sum(!is.na(x$within_CI_Rt))
  summary_bias_k <- summary(x$bias_k, na.rm = TRUE)
  summary_bias_R <- summary(as.vector(x$bias_R), na.rm = TRUE)
  res <- list(cov_k = coverage_k,
              cov_R = coverage_R,
              bias_k = summary_bias_k,
              bias_R = summary_bias_R)
  return(res)
}

performance_metric_fct <- function(replication_sc, res, sim){
  
  performance_metric <- list(bias_k = rep(NA,replication_sc) ,
                             bias_Rt = matrix(NA,nrow = replication_sc, 
                                              ncol = ncol(res$res_MCMC_EpiEstim_Poiss1[[1]]$theta_R) ),
                             within_CI_k = rep(NA,replication_sc) ,
                             within_CI_Rt = matrix(NA,nrow = replication_sc, 
                                                   ncol = ncol(res$res_MCMC_EpiEstim_Poiss1[[1]]$theta_R) ) )
  
  k_true <- res$input$k
  Rt_true <- sim$Rt$Rt[seq(1, nrow(sim$Rt), by = t_window)]
  for(j in 1:replication_sc){
    if(sum_model$Meet_threshold[j]){
      best_model_output <- res[[ sum_model$best_model[j] ]][[j]]
      if(sum_model$best_model[j] == 'res_MCMC_EpiEstim_NB1'){
        performance_metric$bias_k[j] <- mean(best_model_output$theta_over_thinned - k_true)
        
        q_k <- quantile(best_model_output$theta_over_thinned, c(.025,.975))
        performance_metric$within_CI_k[j] <- ((q_k[1] <= k_true) & (q_k[2] >= k_true))
      }
      # Rt performance_metric and within CI
      performance_metric$bias_Rt[j,] <- apply(best_model_output$theta_R_thinned,2,mean) - Rt_true
      q_Rt <- apply(best_model_output$theta_R_thinned,2,quantile, c(.025,.975),na.rm = TRUE)
      performance_metric$within_CI_Rt[j,] <- ((q_Rt[1,] <= Rt_true) & (q_Rt[2,] >= Rt_true))
      
    }
  }
  return(performance_metric)
}

process_estimate <- function(res, threshold_case){
  # browser()
  # 

  replication_sc <- length(res$res_MCMC_EpiEstim_Poiss1)
  sum_model <- data.frame(DIC_Pois1 = rep(NA,replication_sc),
                     DIC_NB1= rep(NA,replication_sc),
                     N_cases = NA,
                     Meet_threshold = NA,
                     best_model = NA)
  for(k in 1:replication_sc){
    sum_model$N_cases[k] <- sum(res$res_EpiEstim[[k]][[1]]$incidence)
    sum_model$Meet_threshold[k] <-  sum_model$N_cases[k] >= threshold_case
    if(sum_model$Meet_threshold[k]){
      sum_model$DIC_Pois1[k] <-  res$res_MCMC_EpiEstim_Poiss1[[k]]$DIC[1]
      sum_model$DIC_NB1[k] <- res$res_MCMC_EpiEstim_NB1[[k]]$DIC[1] 
      if(sum_model$DIC_Pois1[k] > sum_model$DIC_NB1[k]){
        sum_model$best_model[k] <- 'res_MCMC_EpiEstim_NB1'
      }else{
        sum_model$best_model[k] <- 'res_MCMC_EpiEstim_Poiss1'
      }
    }
  }
  
  return(sum_model)
  
}

model_selection_summary <- function(sum_model){
  # browser()
  prop_NB <- mean(sum_model$DIC_Pois1>sum_model$DIC_NB1,na.rm=TRUE)
  N_meet_threshold <- sum(!is.na(sum_model$DIC_Pois1))
  f_meet_threshold <- which(sum_model$Meet_threshold)
  
  outbreak_size_stats <- quantile(sum_model$N_cases[f_meet_threshold],c(.5,0,1))
  
  return(list(outbreak_size_stats = outbreak_size_stats,
              N_meet_threshold = N_meet_threshold,
              prop_NB = prop_NB  ))
}

 
```

```{r}
sum_model    <- process_estimate(res = res, threshold_case = 10)
  m_sel        <- model_selection_summary(sum_model = sum_model)
  input_params <- Scenarios[Scenarios$Scenario==i,]

 performance_metric <- performance_metric_fct(replication_sc, res, sim)
  sp                 <- summary_performance(performance_metric)
  
  sp
```


```{r}

# parameters
# for EpiEstim
t_window <- 7
mean_prior <- 5
std_prior <- 5

res_EpiEstim <- fct_EpiEstim(I0_t_import = sim$I0$timespan , 
                             I = sim$res[[1]]$I_obs, #I_true ,
                             t_window = t_window, 
                             mean_prior = mean_prior, 
                             std_prior = std_prior,
                             si = si, 
                             overlap = FALSE)


plot(Rt$t,Rt$Rt,type = 'l', ylim = c(0,2.5))

for(i in 1:sim$input$n_locations){
  
  Hmisc::errbar(x = res_EpiEstim[[i]]$t_start, 
                y = res_EpiEstim[[i]]$`Median(R)`,
                yplus = res_EpiEstim[[i]]$`Quantile.0.975(R)`,
                yminus = res_EpiEstim[[i]]$`Quantile.0.025(R)`,
                col = i, errbar.col = i, 
                add=TRUE)
}



```


## Run MCMCEpiEstim 

```{r}

rep <- 1e3
devtools::load_all(".")
res_MCMC_EpiEstim_Poiss1 <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan , 
                                              I = sim$res[[1]]$I_true ,
                                              t_window = t_window,
                                              mean_prior = mean_prior, 
                                              std_prior = std_prior,
                                              res_EpiEstim = res_EpiEstim, 
                                              overdispersion = FALSE, 
                                              rep = rep, 
                                              thin = 10, 
                                              param_agg = TRUE, 
                                              p_reps = 1,
                                              overlap = FALSE)

res_MCMC_EpiEstim_Poiss2 <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan , 
                                              I = sim$res[[1]]$I_true , 
                                              t_window = t_window,
                                             mean_prior = mean_prior, std_prior = std_prior,
                                             res_EpiEstim = res_EpiEstim, overdispersion = FALSE, 
                                             rep = rep, thin = 10, param_agg = TRUE, p_reps = input$pi,
                                              overlap = FALSE)


res_MCMC_EpiEstim_NB1 <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan , 
                                           I = sim$res[[1]]$I_true  ,
                                           t_window = t_window,
                                          mean_prior = mean_prior, std_prior = std_prior,
                                          res_EpiEstim = res_EpiEstim, overdispersion = TRUE,
                                          rep = rep, thin = 10, param_agg = TRUE, p_reps = 1,
                                              overlap = FALSE)

res_MCMC_EpiEstim_NB2 <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan , 
                                           I = sim$res[[1]]$I_true  ,
                                           t_window = t_window,
                                          mean_prior = mean_prior, std_prior = std_prior,
                                          res_EpiEstim = res_EpiEstim, overdispersion = TRUE,
                                          rep = rep, thin = 10, param_agg = TRUE, p_reps = input$pi,
                                              overlap = FALSE)



```


check turncations
```{r}


I_trunc <- truncate_incidence(I0_t_import = sim$I0$timespan , 
                             I = sim$res$I_true ,
                             t_window = t_window,
                             incidence_truncate = 1e5)



res_MCMC_EpiEstim_Poiss1 <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan , 
                                              I = I_trunc ,
                                              t_window = t_window,
                                              mean_prior = mean_prior, 
                                              std_prior = std_prior,
                                              res_EpiEstim = res_EpiEstim, 
                                              overdispersion = FALSE, 
                                              rep = rep, 
                                              thin = 10, 
                                              param_agg = TRUE, 
                                              p_reps = 1,
                                              overlap = FALSE)

res_MCMC_EpiEstim_NB1 <- fct_MCMC_EpiEstim(I0_t_import = sim$I0$timespan , I = I_trunc  ,
                                           t_window = t_window,
                                          mean_prior = mean_prior, std_prior = std_prior,
                                          res_EpiEstim = res_EpiEstim, overdispersion = TRUE,
                                          rep = rep, thin = 10, param_agg = TRUE, p_reps = 1,
                                              overlap = FALSE)

aa=res_MCMC_EpiEstim_Poiss1$theta_R_thinned
I = sim$res$I_obs
```

```{r}

dics <- data.frame(model = c('Pois1','Pois2','NB1','NB2'),
                   DIC = c(res_MCMC_EpiEstim_Poiss1$DIC[1],
                           res_MCMC_EpiEstim_Poiss2$DIC[1],
                           res_MCMC_EpiEstim_NB1$DIC[1],
                           res_MCMC_EpiEstim_NB2$DIC[1]))
dics
res_MCMC_EpiEstim_NB1$DIC
```


## check

```{r}
LogL <- cbind(rowSums(res_MCMC_EpiEstim_NB1$logL),
              rowSums(res_MCMC_EpiEstim_NB2$logL))
R1 <- cbind(res_MCMC_EpiEstim_NB1$theta_R[,1],
            res_MCMC_EpiEstim_NB2$theta_R[,1])

layout(matrix(1:4,2,2))
plot(LogL[,1],ylim = range(c(LogL)))
lines(LogL[,2],col = 'red3',type = 'p',pch = 12)
# lines(LogL[,3],col = 'blue3',type = 'p',pch = 12)
# lines(LogL[,4],col = 'green3',type = 'p',pch = 12)

plot(R1[,1],ylim = range(c(R1)))
lines(R1[,2],col = 'red3',type = 'p',pch = 12)
# lines(R1[,3],col = 'blue3',type = 'p',pch = 12)
# lines(R1[,4],col = 'green3',type = 'p',pch = 12)


# others
# acf(res_MCMC_EpiEstim_Poiss1$theta_R[,1])
acf(res_MCMC_EpiEstim_NB1$theta_R[,1])

plot(res_MCMC_EpiEstim_NB1$theta_over , 
     ylim = range(c(res_MCMC_EpiEstim_NB1$theta_over,
                    res_MCMC_EpiEstim_NB2$theta_over)))

lines(res_MCMC_EpiEstim_NB2$theta_over,col = 'red3',type = 'p',pch = 12)

quantile(res_MCMC_EpiEstim_NB1$theta_over_thinned, c(.5,.025,.975))
quantile(res_MCMC_EpiEstim_NB2$theta_over, c(.5,.025,.975))

```


```{r}
k=1
n_location <- sim$input$n_locations
layout(matrix(1:4,2,2))
for(i in 1:n_location){
  plot(res_MCMC_EpiEstim_Poiss1$theta_R[,1])
}

layout(matrix(1:4,2,2))
for(i in 1:n_location){
  plot(res_MCMC_EpiEstim_Poiss2$theta_R[,1])
}

layout(matrix(1:4,2,2))
for(i in 1:n_location){
  plot(res_MCMC_EpiEstim_NB1$theta_R[,1])
}

layout(matrix(1:4,2,2))
for(i in 1:n_location){
  plot(res_MCMC_EpiEstim_NB2$theta_R[,1])
}
```

```{r}
# function for plots compare results
t_max <- length(res_EpiEstim[[1]]$t)
n_location <- sim$input$n_locations
overlap <- FALSE
#time windows
t_start <- seq(sim$I0$timespan+1, t_max-t_window+1,by = 1)
if (overlap == FALSE) {
  t_start <- t_start[seq(1,length(t_start),by = t_window)]
}else{
  
}
t_end <- t_start + t_window - 1   
n_tw <- length(t_start)
 
comp_plot <- function(f1,f2){
  
  if(f2 %in% c("Quantile.0.025(R)","Quantile.0.975(R)")){
    if(f2 %in%"Quantile.0.025(R)"){
      # Rts_mcmc_pois <- apply(res_MCMC_EpiEstim_Poiss1$theta_R,2,quantile,0.025,na.rm = TRUE)
      Rts_mcmc_NB1 <- apply(res_MCMC_EpiEstim_NB1$theta_R_thinned,2,quantile,0.025,na.rm = TRUE)
      Rts_mcmc_NB2 <- apply(res_MCMC_EpiEstim_NB2$theta_R_thinned,2,quantile,0.025,na.rm = TRUE)
    }else{
      # Rts_mcmc_pois <- apply(res_MCMC_EpiEstim_Poiss1$theta_R,2,quantile,0.975,na.rm = TRUE)
      Rts_mcmc_NB1 <- apply(res_MCMC_EpiEstim_NB1$theta_R_thinned,2,quantile,0.975,na.rm = TRUE)
      Rts_mcmc_NB2 <- apply(res_MCMC_EpiEstim_NB2$theta_R_thinned,2,quantile,0.975,na.rm = TRUE)
    }
  }else{
    # Rts_mcmc_pois <- apply(res_MCMC_EpiEstim_Poiss1$theta_R,2,f1)
    Rts_mcmc_NB1 <- apply(res_MCMC_EpiEstim_NB1$theta_R_thinned,2,f1)
    Rts_mcmc_NB2 <- apply(res_MCMC_EpiEstim_NB2$theta_R_thinned,2,f1)
  }
  Rts_epiestim <- matrix(unlist(lapply(res_EpiEstim, "[", ,f2)), nrow = t_max, ncol = n_location, byrow = FALSE)
  Rts_epiestim <- c(Rts_epiestim[t_end,])
  
  if(length(Rts_epiestim) == n_location*length(Rts_mcmc_NB1)){
    # Rts_mcmc_pois <- rep(Rts_mcmc_pois,n_location)
    Rts_mcmc_NB1 <- rep(Rts_mcmc_NB1,n_location)
    Rts_mcmc_NB2 <- rep(Rts_mcmc_NB2,n_location)
  }
  .limits <- range(log10(Rts_epiestim), log10(Rts_mcmc_NB1))
  plot(log10(Rts_epiestim), log10(Rts_mcmc_NB1), bty = 'n', main = f2, col = 'blue3',pch=3, xlim = .limits, ylim = .limits)
  lines(log10(Rts_epiestim), log10(Rts_mcmc_NB2), type = 'p', col = 'red3',pch=4)
  abline(a = c(0,1), col = 'grey50')
  # range((Rts_epiestim-Rts_mcmc), na.rm = TRUE)
  
}


layout(matrix(1:9,3,3, byrow = TRUE))
comp_plot(f1 = mean,f2 = 'Mean(R)')
comp_plot(f1 = median,f2 = "Median(R)")
comp_plot(f1 = sd,f2 = "Std(R)")
comp_plot(f1 = mean,f2 = "Quantile.0.025(R)")
comp_plot(f1 = mean,f2 = "Quantile.0.975(R)")

legend('topleft',c('NB1','NB2'),pch = c(3,4), col = c('blue3', 'red3'),bty = 'n')
legend('topleft',c('NB1','NB2'),pch = c(3,4), col = c('blue3', 'red3'),bty = 'n')

```



```{r}
layout(matrix(1:4,2,2))

# sim vs  epiestim
Rts_epiestim_med <- matrix(unlist(lapply(res_EpiEstim, "[", ,"Median(R)")), 
                           nrow = t_max, ncol = n_location, byrow = FALSE)
Rts_epiestim_mean <- matrix(unlist(lapply(res_EpiEstim, "[", ,"Mean(R)")), 
                            nrow = t_max, ncol = n_location, byrow = FALSE)

plot(rep(seq(1,t_max),n_location),c(Rts_epiestim_med), 
     main = 'median/mean EpiEstim vs sim',bty = 'n',pch=3,col = 'blue3')
lines(rep(seq(1,t_max),n_location),c(Rts_epiestim_mean),type = 'p',pch=4, col = 'red3')
lines(Rt$t, Rt$Rt, col = 'grey50')

# sim vs MCMC Poiss
Rts_mcmc_poiss_med <- matrix(apply(res_MCMC_EpiEstim_Poiss1$theta_R_thinned,2,median), 
                             nrow =  n_tw, ncol = n_location, byrow = FALSE)
Rts_mcmc_poiss_mean <- matrix(apply(res_MCMC_EpiEstim_Poiss1$theta_R_thinned,2,mean), 
                              nrow =  n_tw, ncol = n_location, byrow = FALSE)

plot(rep(t_end,n_location),c(Rts_mcmc_poiss_med), 
     main = 'median/mean MCMC Pois vs sim',bty = 'n',pch=3,col = 'blue3')
lines(rep(t_end,n_location),c(Rts_mcmc_poiss_mean),type = 'p',pch=4, col = 'red3')
lines(Rt$t, Rt$Rt, col = 'grey50')

# sim vs MCMC NB
Rts_mcmc_NB_med <- matrix(apply(res_MCMC_EpiEstim_NB1$theta_R,2,median), 
                             nrow =  n_tw, ncol = n_location, byrow = FALSE)
Rts_mcmc_NB_mean <- matrix(apply(res_MCMC_EpiEstim_NB1$theta_R,2,mean), 
                              nrow =  n_tw, ncol = n_location, byrow = FALSE)

plot(rep(t_end,n_location),c(Rts_mcmc_NB_med), 
     main = 'median/mean MCMC NB vs sim',bty = 'n',,pch=3,col = 'blue3')
lines(rep(t_end,n_location),c(Rts_mcmc_NB_mean),type = 'p',pch=4, col = 'red3')
lines(Rt$t, Rt$Rt, col = 'grey50')

legend('topleft',c('median','mean'),pch = c(3,4), col = c('blue3','red3'),bty = 'n')

```
